services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: pump-app-prod
    restart: always
    working_dir: /var/www
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "ptrei-app04.postgres.database.azure.com:10.0.1.4"
      - "api.telegram.org:149.154.167.220"
    dns:
      - 168.63.129.16
    networks:
      - iot-net
networks:
  iot-net:
    external: true
