services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: pump-app-prod
    restart: always
    working_dir: /var/www
    ports:
      - "8080:80" # Host 8080 maps to Container 80
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "ptrei-app04.postgres.database.azure.com:10.0.1.4"
    networks:
          - iot-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  iot-net:
    external: true