services:
  # PHP Application (Now includes Apache Web Server)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: pump-app-prod
    restart: always
    working_dir: /var/www
    # Apache inside the container will bind to Port 80 on your Ubuntu host
    network_mode: "host"
    extra_hosts: 
      - "ptrei-app04.postgres.database.azure.com:10.0.1.4"